config/routes.rb
DnsJournal::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root 'home#index'

  devise_for :users, :controllers => {:sessions => "sessions"}

  get "home/index"

  resources :domains do
    resources :dns_zones, :only => [:new, :create, :destroy, :show, :edit, :update] do
      resources :soa_sections, :only => [:edit, :create, :update, :destroy]
      resources :resource_records, :only => [:new, :show, :edit, :create, :update, :destroy]
    end
  end

  get 'resource_record_description/:type' => 'resource_records#resource_record_description', as: :resource_record_description

  get '/domains/:id/export/:dns_zone' => 'domains#export_zone', as: :export
  get '/domains/:id/select/:dns_zone' => 'domains#select_dns_zone', as: :select

end

app/models/dns_zone.rb
class DnsZone < ActiveRecord::Base
  include ActiveModel::Validations

  belongs_to :domain
  belongs_to :user
  has_one :soa_section, :dependent => :destroy
  has_many :resource_records, :dependent => :destroy

  validates :user_id, :presence => { :message => "user owner is required" }
  validates :origin, :presence => { :message => "origin is required" }
  validates :origin, :uniqueness => { :if => :first?, :scope => :user, :message => 'origin must be unique for the user'}
  validates :ttl, :numericality => { :only_integer => true }, :allow_nil => true
  validates :admin_email, :email => {:message => "invalid email"}, :allow_blank => true
  validates_format_of :origin, :with => /\A[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(\/.*)?\z/ix, :message => "name must include the Top-Level domain name: example.com"

  scope :max_version, -> { DnsZone.where(:origin => self[:origin]).order("version DESC").first }
  scope :last_by_origin, -> { DnsZone.where(:origin => self[:origin]).order( "updated_at DESC" ).first }
  scope :owned_by, ->(user_id) { where(user_id: user_id) }

  after_initialize :init

  def init
    self.version  ||= 1
    self.ttl ||= 14400
  end

  def new_version
     DnsZone.where(:origin => origin).order( "version DESC" ).first.version + 1
  end

  def first?
    version == 1
  end

  def deep_clone
    new_dns_zone = self.dup
    new_dns_zone.soa_section = self.soa_section.dup if self.soa_section
    Array(self.resource_records).each do |rr|
      new_dns_zone.resource_records << rr.dup
    end
    new_dns_zone
  end

end

app/controllers/dns_zones_controller.rb
class DnsZonesController < ApplicationController
  before_action :set_dns_zone, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource :domain, :find_by => :slug
  load_and_authorize_resource :dns_zone, :through => :domain

  # GET /dns_zones
  # GET /dns_zones.json
  def index
    @dns_zones = DnsZone.all
  end

  # GET /dns_zones/1
  # GET /dns_zones/1.json
  def show
    @soa_section = @dns_zone.soa_section || @dns_zone.build_soa_section(
      mname: "#{@dns_zone.origin}".concat('.'),
      rname: "administrator.#{@dns_zone.origin}".concat('.')
    )
  end

  # GET /dns_zones/new
  def new
    @dns_zone = DnsZone.new(:version => 1)
  end

  # GET /dns_zones/1/edit
  def edit
  end

  # POST /dns_zones
  # POST /dns_zones.json
  def create
    @domain = Domain.friendly.find(params[:domain_id])
    @dns_zone = @domain.dns_zones.create(dns_zone_params.merge({:version => 1}))
    if @dns_zone.save
      redirect_to @domain, notice: 'Dns zone was successfully created.'
    else
      render action: 'edit', @errors => @dns_zone.errors, alert: "Dns zone validation failed."
    end
  end

  # PATCH/PUT /dns_zones/1
  # PATCH/PUT /dns_zones/1.json
  def update
    respond_to do |format|
      zone = @dns_zone.deep_clone
      if (zone.update(dns_zone_params.merge( {:version => @dns_zone.new_version} ))) && zone.valid?
        zone.save!
        @dns_zone.domain.dns_zones << zone
        format.html { redirect_to @dns_zone.domain, notice: 'Dns zone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html do
          flash[:alert] = "Dns zone validation failed."
          @dns_zone = zone
          render action: :edit
        end
        format.json { render json: @dns_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dns_zones/1
  # DELETE /dns_zones/1.json
  def destroy
    respond_to do |format|
      # if @dns_zone.domain.dns_zone != @dns_zone && @dns_zone.destroy
      if @dns_zone.destroy
        format.html { redirect_to @dns_zone.domain, notice: 'Dns zone was successfully deleted.'  }
        format.json { head :no_content }
      else
        format.html { redirect_to @dns_zone.domain, alert: 'Dns_zone in use!' }
        format.json { render json: @tag, status: :has_nodes }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dns_zone
      unless @dns_zone = current_user.dns_zones.where(id: params[:id]).first
        flash[:alert] = 'DnsZone not found.'
        redirect_to domains_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dns_zone_params
      params.require(:dns_zone).permit(:admin_email, :version, :origin, :ttl, :description, :user_id).tap do |dns_zone_params|
        dns_zone_params.merge!({:user_id => current_user.id})
      end
    end
end

app/helpers/dns_zones_helper.rb
module DnsZonesHelper
  def print_errors
     @dns_zone.errors.messages
  end

  def seconds_to_readable_time(seconds)
    mm, ss = seconds.divmod(60)
    hh, mm = mm.divmod(60)
    dd, hh = hh.divmod(24)
    string =
    if dd > 0
      "%d days, %d hours, %d minutes, %d seconds" % [dd, hh, mm, ss]
    elsif hh > 0
      "%d hours, %d minutes, %d seconds" % [hh, mm, ss]
    elsif mm > 0
      "%d minutes, %d seconds" % [mm, ss]
    else
      "%d seconds" % ss
    end
    string
  end
end

app/views/dns_zones/_code_tag.html.haml
%code
  = "#{dns_zone.soa_section.primary_domain_name} #{dns_zone.soa_section.zone_class} SOA #{dns_zone.soa_section.mname} #{dns_zone.soa_section.rname} ("
  %br
  &emsp;&emsp;&emsp;&emsp;
  = precede " #{dns_zone.soa_section.serial_number} " do
    / &emsp;&emsp;&emsp;
    = "; serial number"
  %br
  &emsp;&emsp;&emsp;&emsp;
  = precede " #{dns_zone.soa_section.refresh} " do
    / &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    = "; refresh after #{seconds_to_readable_time dns_zone.soa_section.refresh}"
  %br
  &emsp;&emsp;&emsp;&emsp;
  = precede " #{dns_zone.soa_section.retry} " do
    / &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    = "; retry after #{seconds_to_readable_time dns_zone.soa_section.retry}"
  %br
  &emsp;&emsp;&emsp;&emsp;
  = precede " #{dns_zone.soa_section.expire} " do
    / &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    = "; expire after #{seconds_to_readable_time dns_zone.soa_section.expire}"
  %br
  &emsp;&emsp;&emsp;&emsp;
  = precede " #{dns_zone.soa_section.minimum} " do
    / &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    = "; minimum TTL"
  %br
  = ") ;"

app/views/dns_zones/_form.html.haml
= simple_form_for([@dns_zone.domain, @dns_zone]) do |f|
  - if @dns_zone.errors.any?
    = render 'layouts/error_explanation', resource: @dns_zone, name: 'dns zone'
  .row
    .large-8.columns
      .field
        %span.has-tip{"data-tooltip" => "", :title => " $ORIGIN must include the Top-Level domain name: example.com"}
          = f.label '$ORIGIN:'
        = f.text_field :origin, required: 'true'
    .large-4.columns
      .field
        = f.label 'TTL (seconds)'
        = f.number_field :ttl
  .field
    = f.label :admin_email
    %br
      = f.text_field :admin_email
  .field
    = f.label :description
    %br
      = f.text_area :description
  .actions
    = f.submit 'save', :class => "button"

app/views/dns_zones/_rr_form.html.haml
= simple_form_for [@dns_zone.domain, @dns_zone, @resource_record ||= ResourceRecord.new] do |f|
  - if @resource_record.errors.any?
    = render 'layouts/error_explanation', resource: @resource_record, name: 'resource record'
  .row
    .large-3.columns
      = f.label :resource_type, class: "right inline"
    .large-3.columns.left
      .select_rr_type
        = f.input :resource_type, collection: ResourceRecord.available_resource_types.keys, include_blank: true, required: true, input_html: {:data => {:purpose => "show-types"}}, label: false
    .rr_option
      .large-3.columns
        %span.has-tip{"data-tooltip" => "", :title => "an MX require a priority value"}
          = f.label :option, class: "right inline"
      .large-3.columns
        = f.number_field :option
  .rr_name
    .row
      .large-3.columns
        = f.label :name, class: "right inline"
      .large-9.columns
        = f.text_field :name
  .row
    .large-3.columns
      = f.label :value, class: "right inline"
    .large-9.columns
      = f.text_field :value
  .row
    .large-3.columns.large-offset-3
      = f.submit "Save", :class => "button"

app/views/dns_zones/edit.html.haml
%h1
  Editing dns_zone
  = @dns_zone.origin
  %h3
    (version
    = succeed ')' do
      = @dns_zone.version
= render 'form'
- if @dns_zone.new_record?
  = link_to 'Cancel', domain_path(@dns_zone.domain)
- else
  = link_to 'Back', domain_dns_zone_path(@dns_zone.domain, @dns_zone)

app/views/dns_zones/new.html.haml
%h1 New dns_zone
- if @dns_zone.errors.any?
  = render 'layouts/error_explanation', resource: @dns_zone, name: 'dns_zone'
= link_to 'Back', domain_path(@domain.id)

app/views/dns_zones/show.html.haml
#dns_zone_section
  .row
    .large-12.columns
      %h3
        Domain: #{link_to "#{@dns_zone.domain.name}", domain_path(@dns_zone.domain)}
      %p.little_info
        Created:
        = @dns_zone.domain.created_at.strftime('%d.%m.%Y %H:%M')
        ;
        Last update:
        = @dns_zone.domain.updated_at.strftime('%d.%m.%Y %H:%M')

  .row
    %fieldset
      %legend
        DNS_ZONE for #{@dns_zone.origin}
      .large-8.columns
        .panel
          %code
            $ORIGIN #{@dns_zone.origin} ;
            %br
            $TTL #{@dns_zone.ttl} ;
            %br
            ; Admin email: #{@dns_zone.admin_email}
      .large-4.columns
        %ul.button-group
          %li
            = link_to edit_domain_dns_zone_path(@dns_zone.domain, @dns_zone) do
              %i{class: "fi-pencil"}
                %span
                  edit
.row
  #soa_section
    %fieldset
      %legend Start of Authority (SOA)
      - unless @dns_zone.soa_section.new_record?
        .panel
          = render 'code_tag', dns_zone: @dns_zone
        %p
          = link_to edit_domain_dns_zone_soa_section_path(@dns_zone.domain, @dns_zone, @dns_zone.soa_section) do
            %i{class: "fi-pencil"}
              %span edit
          = precede ' | ' do
            = link_to domain_dns_zone_soa_section_path(@dns_zone.domain, @dns_zone, @dns_zone.soa_section), method: :delete, data: { confirm: 'Are you sure?' } do
              %i{class: "fi-trash"}
                %span delete
      - else
        = render 'soa_sections/form'
  .rr_section
    %fieldset
      %legend
        Resource Records (RR)
      .rr_section_content
        - unless @dns_zone.resource_records.empty?
          .panel
            %code
              - Array(@dns_zone.resource_records).each do |rr|
                = rr.to_code_string
                %br
          %table
            %thead
              %tr
                %th Name
                %th
                %th Type
                %th Value
                %th Option
            %tbody
              - @dns_zone.resource_records.each do |rr|
                %tr
                  %td= rr.name
                  %td IN
                  %td
                    %span.has-tip{"data-tooltip" => "", :title => ResourceRecord.tooltips[rr.resource_type]}
                      = rr.resource_type
                  %td= rr.value
                  %td= rr.option
                  %td
                    %li= link_to "#{rr.rfc}", "#{rr.link_rfc}"
                    %li= link_to 'Details', domain_dns_zone_resource_record_path(@dns_zone.domain, @dns_zone, rr)
                    %li= link_to 'Destroy', domain_dns_zone_resource_record_path(@dns_zone.domain, @dns_zone, rr), method: :delete, data: { confirm: 'Are you sure?' }
      %fieldset
        %legend
          New Resource Record
          / = precede ' - ' do
          /   = link_to 'Show more', '#', :id => 'hide_rr_section'
        .rr_section_form
          = render 'rr_form'
%ul.button-group
  %li= link_to 'Back', domain_path(@dns_zone.domain)