config/routes.rb
DnsJournal::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root 'home#index'

  devise_for :users, :controllers => {:sessions => "sessions"}

  get "home/index"

  resources :domains do
    resources :dns_zones, :only => [:new, :create, :destroy, :show, :edit, :update] do
      resources :soa_sections, :only => [:edit, :create, :update, :destroy]
      resources :resource_records, :only => [:new, :show, :edit, :create, :update, :destroy]
    end
  end

  get 'resource_record_description/:type' => 'resource_records#resource_record_description', as: :resource_record_description

  get '/domains/:id/export/:dns_zone' => 'domains#export_zone', as: :export
  get '/domains/:id/select/:dns_zone' => 'domains#select_dns_zone', as: :select

end

app/models/domain.rb
class Domain < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :dns_zones, :dependent => :destroy

  validates :user_id, presence: true
  validates :name, :presence => true
  validates_uniqueness_of :name, :scope => :user_id
  # validates_format_of :name, :with => /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix, :message => "name must be in domain format: http(s)://www.example.com"

  def dns_zone
    DnsZone.find(current_dns_zone) if current_dns_zone
  end

  def last_dns_zone
    DnsZone.where(:domain_id => self.id).last
    # gotcha:
    # :joins set :updateonly => true !
    #DnsZone.joins(:domain).where('domains.id' => self.id).last
  end

end

app/controllers/domains_controller.rb
require 'tempfile'
require 'zone_file_generator'

class DomainsController < ApplicationController

  # Gotcha! Custom find here...
  before_action :set_domain, only: [:show, :edit, :update, :destroy, :export_zone]
  before_filter :authenticate_user!
  load_and_authorize_resource only: [:show, :edit, :update, :destroy, :export_zone]

  # GET /domains
  # GET /domains.json
  def index
    @domains = current_user.domains || []
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params.merge({:user_id => current_user.id}))
    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render action: 'show', status: :created, location: @domain }
      else
        format.html { render action: 'new' }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html do
        redirect_to domains_url, notice: 'Domain deleted.'
      end
      format.json { head :no_content }
    end
  end

  def select_dns_zone
    set_domain
    dns_zone = DnsZone.find_by(id: params[:dns_zone])
    respond_to do |format|
      if dns_zone && dns_zone.soa_section && (@domain.current_dns_zone = params[:dns_zone]) && @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @domain, alert: 'Dns Zone without SOA section!' }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  def export_zone
    dns_zone = DnsZone.find(params[:dns_zone])
    respond_to do |format|
      if dns_zone
        format.html do
          begin
            file_content = ZoneFileGenerator.generate_file_content(dns_zone, DnsJournal::Application::VERSION)
            send_data( file_content, :filename => "#{@domain.name}.txt" )
            flash[:notice] = 'File exported'
          rescue Exception => e
            flash[:alert] = "Something went wrong... (#{e.message})"
          ensure
            # can't render the flash?
          end
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      unless @domain = Domain.friendly.find(params[:id])
        flash[:alert] = 'Domain not found.'
        redirect_to domains_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:name, :note)
    end

end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_dns_zone_form.haml
= simple_form_for [@domain, DnsZone.new] do |f|
  .row
    .large-2.columns
      = f.label :origin, "$ORIGIN:", class: 'right inline'
    .large-10.columns
      = f.text_field :origin, required: 'true'
  .row
    .large-12.columns.centered_content
      = f.submit "create Dns Zone", class: 'button'

app/views/domains/_form.html.haml
= simple_form_for(@domain) do |f|
  - if @domain.errors.any?
    = render 'layouts/error_explanation', resource: @domain, name: 'domain'
  .row
    .large-8.columns
      = f.label :name
      %br
        = f.text_field :name, placeholder: "...", required: true
  .row
    .large-8.columns
      = f.label :note
      %br
        = f.text_area :note, placeholder: "..."
  .row
    .large-8.columns
      .actions
        = f.submit nil, class: "button"
        = link_to 'Back', @domain, class: "button right"

app/views/domains/edit.html.haml
%h2
  = @domain.name
= render 'form'

app/views/domains/index.html.haml
%h1
  Your domains
%ul
  - @domains.each do |domain|
    %li
      = link_to "#{domain.name}", domain
      - if domain.current_dns_zone
        using
        = link_to "#{domain.dns_zone.origin}", domain_dns_zone_path(domain,domain.current_dns_zone)
        version #{domain.dns_zone.version}
      = precede ' | ' do
        = link_to domain, method: :delete, data: { confirm: 'Are you sure?' } do
          %i{class: "fi-trash"}
%br
  = link_to 'New Domain', new_domain_path, { :class => "button" }

app/views/domains/new.html.haml
%h1 New domain
= render 'form'

app/views/domains/show.html.haml
.row
  .large-12.columns
    %h2= @domain.name
%p
  %strong Dns Zone (current):
  - if @domain.current_dns_zone
    = link_to "#{@domain.dns_zone.origin}", domain_dns_zone_path(@domain,@domain.current_dns_zone)
    version #{@domain.dns_zone.version}
  - else
    None selected
%fieldset#domain_dns_zones
  %legend
    DNS Zone
  - if @domain.dns_zones.present?
    .dns_zones
      %table
        %thead
          %tr
            %th origin
            %th version
            %th
        %tbody
          - @domain.dns_zones.each do |dns_zone|
            %tr
              %td= dns_zone.origin
              %td= dns_zone.version
              %td
                = link_to 'Show', domain_dns_zone_path(@domain, dns_zone)
                = precede ' | ' do
                  = link_to 'Use', select_path(@domain, dns_zone)
                = precede ' | ' do
                  = link_to 'Destroy', domain_dns_zone_path(@domain, dns_zone), method: :delete, data: { confirm: 'Are you sure?' }
                = precede ' | ' do
                  = link_to 'Export', export_path(@domain, dns_zone)
  - else
    = @errors
    .new_dns_zone
      = render 'dns_zone_form'
.row
  = link_to 'Edit', edit_domain_path(@domain)
  = precede ' | ' do
    = link_to 'Back', domains_path