config/routes.rb
DnsJournal::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root 'home#index'

  devise_for :users, :controllers => {:sessions => "sessions"}

  get "home/index"

  resources :domains do
    resources :dns_zones, :only => [:new, :create, :destroy, :show, :edit, :update] do
      resources :soa_sections, :only => [:edit, :create, :update, :destroy]
      resources :resource_records, :only => [:new, :show, :edit, :create, :update, :destroy]
    end
  end

  get 'resource_record_description/:type' => 'resource_records#resource_record_description', as: :resource_record_description

  get '/domains/:id/export/:dns_zone' => 'domains#export_zone', as: :export
  get '/domains/:id/select/:dns_zone' => 'domains#select_dns_zone', as: :select

end

app/models/resource_record.rb
class ResourceRecord < ActiveRecord::Base
  include ActiveModel::Validations
  belongs_to :dns_zone
  belongs_to :user

  validates :user_id, presence: true
  validates :dns_zone, presence: true
  validates_with ResourceRecordValidator

  before_validation ->{ self.description = self.class.definitions[self.resource_type].join(', ') unless self.description.present? && self.resource_type.blank? }

  class << self

    def available_resource_types
      {
        'A' => 'rfc1035',
        'CNAME' => 'rfc1035',
        'NS' => 'rfc1035',
        'MX' => 'rfc1035',
        'PTR' => 'rfc1035'
      }
    end

    def definitions
      {
        'A' => ['Address Record','Returns a 32-bit IPv4 address, most commonly used to map hostnames to an IP address of the host, but also used for DNSBLs, storing subnet masks in RFC 1101, etc.'],
        'CNAME' => ['Canonical Name Record','Alias of one name to another: the DNS lookup will continue by retrying the lookup with the new name.'],
        'NS' => ['Name Server Record','Delegates a DNS zone to use the given authoritative name servers'],
        'MX' => ['Mail Exchange Record','Maps a domain name to a list of message transfer agents for that domain'],
        'PTR' => ['Pointer Record','Pointer to a canonical name. Unlike a CNAME, DNS processing does NOT proceed, just the name is returned. The most common use is for implementing reverse DNS lookups, but other uses include such things as DNS-SD.']
      }
    end

    def tooltips
      {
        'A' => "hostname IN A IP-address",
        'CNAME' => "alias-name IN CNAME real-name",
        'NS' => "IN NS nameserver-name",
        'MX' => "IN MX preference-value email-server-name",
        'PTR' => "last-IP-digit IN PTR FQDN-of-system"
      }
    end
  end

  def name
    _name = read_attribute(:name) || ''
    # TODO: understand trailing point...
    # _name.concat(".#{dns_zone.origin}") if _name[-1] != '.' && dns_zone
  end

  def to_code_string
    "#{name} IN #{resource_type} #{value} #{option || ''} ;"
  end

  def rfc
    self.class.available_resource_types.fetch(resource_type){''}
  end

  def link_rfc
    URI.parse("http://tools.ietf.org/html/#{rfc}")
  end
end

app/controllers/resource_records_controller.rb
class ResourceRecordsController < ApplicationController

  before_filter :authenticate_user!, except: [:resource_record_description]
  load_and_authorize_resource

  # GET /resource_records/1
  # GET /resource_records/1.json
  def show
  end

  # GET /resource_records/new
  def new
    @domain = Domain.friendly.find(params[:domain_id])
    @dns_zone = DnsZone.find(params[:dns_zone_id])
    @resource_record ||= ResourceRecord.new
    @resource_record.dns_zone = @dns_zone
  end

  # GET /resource_records/1/edit
  def edit
  end

  # POST /resource_records
  # POST /resource_records.json
  def create
    @dns_zone = DnsZone.find(params[:dns_zone_id])
    @resource_record = ResourceRecord.new(resource_record_params.merge({ user_id: current_user.id, dns_zone_id: @dns_zone.id }))
    respond_to do |format|
      if @resource_record.save
        format.html { redirect_to domain_dns_zone_path(@dns_zone.domain, @dns_zone), notice: 'Resource record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @resource_record }
      else
        format.html { render action: :new }
        format.json { render json: @resource_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resource_records/1
  # PATCH/PUT /resource_records/1.json
  def update
    respond_to do |format|
      if @resource_record.update(resource_record_params)
        format.html { redirect_to domain_dns_zone_path(@resource_record.dns_zone.domain, @resource_record.dns_zone), notice: 'Resource record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :new, alert: "Resource Record validation failed: #{@resource_record.errors.messages}" }
        format.json { render json: @resource_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource_records/1
  # DELETE /resource_records/1.json
  def destroy
    @resource_record.destroy
    respond_to do |format|
      format.html { redirect_to domain_dns_zone_path(@resource_record.dns_zone.domain, @resource_record.dns_zone) }
      format.json { head :no_content }
    end
  end

  def resource_record_description
    render json: ResourceRecord.definitions.fetch(params[:type]){|key| 'key not found' }
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_resource_record
      unless @resource_record = current_user.resource_records.where(id: params[:id]).first
        flash[:alert] = 'ResourceRecord not found.'
        redirect_to domains_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_record_params
      params.require(:resource_record).permit(:name, :resource_type, :value, :rfc, :description, :option)
    end
end

app/helpers/resource_records_helper.rb
module ResourceRecordsHelper
end

app/views/resource_records/_form.html.haml
= simple_form_for [@resource_record.dns_zone.domain, @resource_record.dns_zone, @resource_record] do |f|
  - if @resource_record.errors.any?
    = render 'layouts/error_explanation', resource: @resource_record, name: 'resource record'
  .rr_name
    .field
      .row
        .large-4.columns
          = f.label :name
        .large-8.columns
          = f.text_field :name
  .field
    .row
      .large-4.columns
        = f.label :resource_type
      .large-8.columns
        = f.input :resource_type, collection: ResourceRecord.available_resource_types.keys, include_blank: true, required: true, input_html: {:data => {:purpose => "show-types"}}, label: false
  .field
    .row
      .large-4.columns
        = f.label :value
      .large-8.columns
        = f.text_field :value
  .rr_option
    .field
      .row
        .large-4.columns
          = f.label :option
        .large-8.columns
          = f.number_field :option
  .rr_description
    .field
      .row
        .panel
          .rr_description_panel
            %p
              = ResourceRecord.definitions.fetch(@resource_record.resource_type).first
            %p
              = ResourceRecord.definitions.fetch(@resource_record.resource_type)[1]
  .actions
    .row
      = f.submit 'Save', :class => "button"
      .right
        = link_to 'Back', domain_dns_zone_path(@resource_record.dns_zone.domain, @resource_record.dns_zone), class: 'button'

app/views/resource_records/edit.html.haml
%h1 Edit Resource Record
= render 'form'

app/views/resource_records/new.html.haml
%h1 New Resource Record
= render 'form'

app/views/resource_records/show.html.haml
%p#notice= notice
%p
  %strong Resource Type:
  = @resource_record.resource_type
%p
  %strong Name:
  = @resource_record.name
%p
  %strong Value:
  = @resource_record.value
%p
  %strong Rfc:
  = @resource_record.rfc
%p
  %strong
    Details:
    .panel
      %p
        = ResourceRecord.definitions.fetch(@resource_record.resource_type).first
      %p
        = ResourceRecord.definitions.fetch(@resource_record.resource_type)[1]
%p
  = link_to edit_domain_dns_zone_resource_record_path(@resource_record.dns_zone.domain, @resource_record.dns_zone, @resource_record) do
    %i{class: "fi-pencil"}
      %span edit
  = precede ' | ' do
    = link_to domain_dns_zone_path(@resource_record.dns_zone.domain, @resource_record.dns_zone) do
      %i{class: "fi-arrow-left"}
        %span back