config/routes.rb
DnsJournal::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root 'home#index'

  devise_for :users, :controllers => {:sessions => "sessions"}

  get "home/index"

  resources :domains do
    resources :dns_zones, :only => [:new, :create, :destroy, :show, :edit, :update] do
      resources :soa_sections, :only => [:edit, :create, :update, :destroy]
      resources :resource_records, :only => [:new, :show, :edit, :create, :update, :destroy]
    end
  end

  get 'resource_record_description/:type' => 'resource_records#resource_record_description', as: :resource_record_description

  get '/domains/:id/export/:dns_zone' => 'domains#export_zone', as: :export
  get '/domains/:id/select/:dns_zone' => 'domains#select_dns_zone', as: :select

end

app/views/layouts/_error_explanation.html.haml
.row
  .large-12.columns
    #error_explanation
      .title
        = pluralize(resource.errors.count, "error")
        in this
        = name
      .messages
        %ul
          - resource.errors.full_messages.each do |msg|
            %li= msg

app/views/layouts/_footer.html.haml
.row
  .large-12.columns
    %hr
    = link_to 'Home', home_index_path

app/views/layouts/_side_panel.html.haml
%p.navbar-text.pull-right
  - if alert.present?
    .alert-box.alert.radius{"data-alert" => ""}
      = alert
      %a.close{:href => "#"} &times;
  - if notice.present?
    .alert-box.radius{"data-alert" => ""}
      = notice
      %a.close{:href => "#"} &times;

app/views/layouts/_top_bar.html.haml
.top_bar_with_links
  %nav.top-bar
    %ul.title-area
      %li.name
        %h1
          = link_to 'Dns Journal', home_index_path
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          %span Menu
    %section.top-bar-section
      %ul.left
        %li.divider
      %ul.right
        %li.divider
        %li
          = link_to 'About', page_path('about')
        %li.divider
        %li.has-dropdown
          %a{:href => "#"}
            = user_signed_in? ? 'Menu' : 'SignIn/SignUp'
          %ul.dropdown
            - if user_signed_in?
              %li
                %label Account
              %li
                = link_to 'Edit profile', edit_user_registration_path
              %li
                = link_to "Logout", destroy_user_session_path, :method => :delete, :data => { :confirm => "Are you sure?" }
              %li
                %label
                  Domains (#{current_user.domains.count})
              %li
                = link_to 'domains', domains_path
            - else
              %li
                = link_to "Sign up", new_user_registration_path
              %li
                = link_to "Login", new_user_session_path, :class => 'navbar-link'
            %li
              %label Links
            %li
              = link_to 'RFCs', page_path('rfcs')
            %li.divider

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/ [if (gte IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= title; content_for?(:title) ? yield(:title) : "Untitled"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags
  %body
    .wrapper
      .top_bar_section
        = render 'layouts/top_bar'
      .row
        .large-8.columns
          = yield
        .large-3.offset-large-1.columns.side_panel
          = render 'layouts/side_panel'
      .push
    .footer
      = render 'layouts/footer'